# Generated by Django 3.2.5 on 2022-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eat_better',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('recipe_title', models.CharField(default='', max_length=100)),
                ('recipe_category', models.CharField(default='', max_length=50)),
                ('recipe_dietary_type', models.CharField(default='', max_length=50)),
                ('recipe_serves', models.IntegerField(default=0)),
                ('recipe_prep_time', models.IntegerField(default=0)),
                ('recipe_make_time', models.IntegerField(default=0)),
                ('recipe_calorie', models.CharField(default=0, max_length=40)),
                ('recipe_difficulty', models.CharField(default='', max_length=60)),
                ('recipe_ingredients', models.CharField(default='', max_length=255)),
                ('recipe_steps', models.TextField(default='')),
                ('recipe_infos', models.TextField(default='')),
                ('thumbnail', models.ImageField(default='', upload_to='image/thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='video_content',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('video_title', models.CharField(default='', max_length=100)),
                ('video_category', models.CharField(default='', max_length=50)),
                ('video_duration', models.IntegerField(default=0)),
                ('calorie', models.CharField(default=0, max_length=40)),
                ('w_equipment', models.CharField(default='', max_length=60)),
                ('w_difficulty', models.CharField(default='', max_length=60)),
                ('training_type', models.CharField(default='', max_length=50)),
                ('youtube_link', models.CharField(default='', max_length=200)),
                ('embed_link', models.CharField(default='', max_length=300)),
                ('thumbnail', models.ImageField(default='', upload_to='image/thumbnail')),
                ('video_summary', models.TextField(default='')),
            ],
        ),
    ]
